spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: iloveyou727870
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true